name: recipes
description: Recipe Finder

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.7
  json_annotation: ^4.1.0
  chopper: ^4.0.1
  logging: ^1.0.1
  provider: ^6.0.0
  equatable: ^2.0.3
  sqlbrite: ^2.1.0
  drift: ^1.6.0
  drift_sqflite: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.1
  json_serializable: ^6.1.5
  chopper_generator: ^4.0.1
  drift_dev: ^1.6.0


flutter:

  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
